#include <stdio.h>
#include <stdlib.h>
#include "gba.h"
#include "game.h"
                    /* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

#include "images/enemy.h"
#include "images/titleScreen.h"
#include "images/gamePlayer.h"
#include "images/boss.h"
#include "images/gameOver.h"


                    /* TODO: */
// Add any additional states you need for your app.

typedef enum {
    START,
    PLAY,
    END
} GBAState;


int main(void) {

    //enemy setup
    struct Enemy regEnemies[9];
    for (int i = 0; i < 9; i++) {
        regEnemies[i].enemyX = (20 * i);
        regEnemies[i].enemyY = 0;
    }

    regEnemies[1].enemyX = 240;
    regEnemies[4].enemyX = 240;
    regEnemies[8].enemyX = 240;

    struct Enemy specialEnemies[9];
    for (int i = 0; i < 9; i++) {
        specialEnemies[i].enemyX = (28 * i);
        specialEnemies[i].enemyY = 160;
    }

    specialEnemies[3].enemyX = 240;
    specialEnemies[6].enemyX = 240;

    //player set up
    struct Player player;
    player.playerX = 120;
    player.playerY = 136;


                    /* TODO: */
    // Manipulate REG_DISPCNT here to set Mode 3. //
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    // Load initial game state

    GBAState state = START;

    //Tracking collisions

    int collisions = 0;

    while (1) {
        currentButtons = BUTTONS;
        waitForVBlank();

        switch(state) {

            case START:
                drawFullScreenImageDMA(titleScreen);

                //For resetting when returning after game over screen

                for (int i = 0; i < 9; i++) {
                    regEnemies[i].enemyX = (28 * i);
                    regEnemies[i].enemyY = 0;
                }

                regEnemies[1].enemyX = 240;
                regEnemies[4].enemyX = 240;
                regEnemies[8].enemyX = 240;

                for (int i = 0; i < 9; i++) {
                    specialEnemies[i].enemyX = (28 * i);
                    specialEnemies[i].enemyY = 160;
                }

                specialEnemies[3].enemyX = 240;
                specialEnemies[6].enemyX = 240;

                //player set up
                player.playerX = 120;
                player.playerY = 136;
                collisions = 0;

                if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {

                    state = PLAY;
                }
                break;

            case PLAY:

                fillScreenDMA(CYAN);

                char buf[40];
                snprintf(buf, 40, "COLLISIONS: %d", collisions);
                drawString(25,80,buf, MAGENTA);


                if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {

                    state = START;
                    break;
                }

                //player movement
                if (KEY_DOWN(BUTTON_LEFT, BUTTONS) && (player.playerX > 0)) {
                   player.playerX = player.playerX - pSpeed;

                } else if (KEY_DOWN(BUTTON_RIGHT, BUTTONS) && (player.playerX <= 216)) {
                   player.playerX = player.playerX + pSpeed;

                } else if (KEY_DOWN(BUTTON_UP, BUTTONS) && (player.playerY > 25)) {
                   player.playerY = player.playerY - pSpeed;

                } else if (KEY_DOWN(BUTTON_DOWN, BUTTONS) && (player.playerY <= 136)) {
                   player.playerY = player.playerY + pSpeed;

                }

                //Draw player

                drawImageDMA(player.playerX, player.playerY, 15, 15, gamePlayer);

                int endOfGame = 0;
                int flag = 1;

                for (int i = 0; i < 9; i++) {

                    specialEnemies[i].enemyY = specialEnemies[i].enemyY + eSpeed;

                    //Draw enemy

                    drawImageDMA(specialEnemies[i].enemyX, specialEnemies[i].enemyY, 19, 21, enemy);

                    if (hit(specialEnemies[i].enemyX, specialEnemies[i].enemyY, 15, 15, player.playerX, player.playerY)) {

                        for (int i = 0; i < 9; i++) {
                            regEnemies[i].enemyX = (28 * i);
                            regEnemies[i].enemyY = 0;
                        }

                        regEnemies[1].enemyX = 240;
                        regEnemies[4].enemyX = 240;
                        regEnemies[8].enemyX = 240;

                        for (int i = 0; i < 9; i++) {
                            specialEnemies[i].enemyX = (28 * i);
                            specialEnemies[i].enemyY = 160;
                        }

                        specialEnemies[3].enemyX = 240;
                        specialEnemies[6].enemyX = 240;

                        //player set up
                        player.playerX = 120;
                        player.playerY = 136;
                        collisions++;
                        if(collisions == 3) {
                            state = END;
                            flag = -1;
                        }
                        break;

                    }

                    if (specialEnemies[i].enemyY >= 228) {
                        specialEnemies[i].enemyY = 0;
                    }

                    if ((specialEnemies[i].enemyY >= 200) && (regEnemies[i].enemyY <= 45)) {
                        specialEnemies[i].enemyY = 160;
                    }

                    if ((specialEnemies[i].enemyY >= 200) && (regEnemies[i].enemyY <= 45)) {
                        specialEnemies[i].enemyY = 160;
                    }

                    if ((regEnemies[i].enemyY >= 120) && (specialEnemies[i].enemyY >= 170)) {
                        specialEnemies[i].enemyY = 160;
                    }

                }

                if(flag == -1) {
                    state = END;
                    break;
                }
                if (endOfGame == 1) {
                    break;
                }

                for (int i = 0; i < 9; i++) {
                    regEnemies[i].enemyY = regEnemies[i].enemyY + eSpeed;

                    //Draw enemy

                    drawImageDMA(regEnemies[i].enemyX, regEnemies[i].enemyY, 19, 21, enemy);

                    if (hit(regEnemies[i].enemyX, regEnemies[i].enemyY, 15, 15, player.playerX, player.playerY)) {

                         for (int i = 0; i < 9; i++) {
                            regEnemies[i].enemyX = (28 * i);
                            regEnemies[i].enemyY = 0;
                        }

                        regEnemies[1].enemyX = 240;
                        regEnemies[4].enemyX = 240;
                        regEnemies[8].enemyX = 240;

                        for (int i = 0; i < 9; i++) {
                            specialEnemies[i].enemyX = (28 * i);
                            specialEnemies[i].enemyY = 160;
                        }

                        specialEnemies[3].enemyX = 240;
                        specialEnemies[6].enemyX = 240;

                        //player set up
                        player.playerX = 120;
                        player.playerY = 136;
                        collisions++;
                        if(collisions == 3) {
                            state = END;
                            flag = -1;
                        }
                        break;

                    }

                    if (regEnemies[i].enemyY >= 160) {
                        regEnemies[i].enemyY = 0;
                    }
                }

                break;

            case END:

                drawImageDMA(0, 0, 240, 160, gameOver);

                if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                    state = START;
                }
                if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                    state = START;
                }
                break;

            }
        previousButtons = currentButtons;
    }
    return 0;
}
